version: '3'

services:
  imperative-extractor:
    build: extractor/.
    env_file: extractor/.env
    container_name: imperative-extractor
    image: localhost:32000/imperative-extractor:latest
    depends_on:
    - rabbitmq
    ports:
    - '8080:8080'

  imperative-translator:
    build: translator/.
    env_file: translator/.env
    container_name: imperative-translator
    image: localhost:32000/imperative-translator:latest
    depends_on:
    - rabbitmq
    ports:
    - '8081:8081'

  imperative-loader:
    build: loader/.
    env_file: loader/.env
    container_name: imperative-loader
    image: localhost:32000/imperative-loader:latest
    depends_on:
    - rabbitmq
    ports:
    - '8082:8082'

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - 5672:5672
    - 15672:15672